### ISSUE TITLE
Strip echo of the dump command

### ISSUE THREAD

**Issue by theus77** [ems-project/elasticms-docker#5]
When I run this command 
`docker-compose exec ems_mysql $1 dump > /mnt/backups/theus/dumps/$1_$(date +%u).sql` 
the first line of the output is the dump command itself (pgdump..., mysqldump..). 

I solved this by running those commands
`docker-compose exec ems_mysql $1 dump | sed "/^mysqldump.*$/d" > /mnt/backups/theus/dumps/$1_$(date +%u).sql` 

or this 

`docker-compose exec ems_pgsql $1 dump | sed "/^PGHOST.*$/d" > /mnt/backups/theus/dumps/$1_$(date +%u).sql`

But it's an hack.

**Comment by zebby76** [comment]
echo command has been removed from generated script. See https://github.com/ems-project/elasticms-docker/pull/8 PR .
